version: "3"

services:
  api_php:
    build: php-fpm/.
    container_name: ${APP_NAME}_php
    volumes:
      - ${APP_PATH}:/app
    networks:
      - network
  api_web:
    image: nginx:1.13
    container_name: ${APP_NAME}_web
    ports:
      - ${HOST_APP_PORT}:80
    volumes:
      - ${APP_PATH}:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
  api_db:
    build: mysql/.
    container_name: ${APP_NAME}_mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - ${DATABASE_DIR}:/var/lib/mysql
    ports:
      - ${HOST_DB_PORT}:3306
    networks:
      - network
networks:
  network:
